spring:
  application:
    name: product-service
  profiles:
    active: dev
info:
  version: ${project.version}
management:
  endpoint:
    shutdown:
      enabled: true
server:
  port: 8080
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      # Eureka server address
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true  
mongeez:
  location: mongo-changelog/changelog-master.xml
---
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      database: product-service


